services:
  avalanche:
    image: avaplatform/avalanchego
    container_name: avax
    command:
      [
        "/avalanchego/build/avalanchego",
        "--db-dir=/data/avax",
        "--http-host=0.0.0.0",
        "--http-allowed-hosts=*"
      ]
    ports:
      - 9650:9650
      - 9651:9651
    volumes:
      - ./staking/staker.key:/root/.avalanchego/staking/staker.key
      - ./staking/staker.cert:/root/.avalanchego/staking/staker.crt
    restart: unless-stopped
